### ISSUE TITLE
'Innovative concert' link points to wrong URL

### ISSUE THREAD

**Issue by pickleshy** [nkkl/orchestral#11]
Points to: https://orchestral.herokuapp.com/livemusicproject.org/event/seattle-collaborative-orchestra-listen-to-the-girls/

Should point to http://livemusicproject.org/event/seattle-collaborative-orchestra-listen-to-the-girls/

**Comment by nkkl** [comment]
Fixed in https://github.com/nkkl/orchestral/commit/56f35d44fb35dfbb20a6bae2670dc68623fb7a10
