### ISSUE TITLE
Using browser button to go back to orchestral.herokuapp.com returns textual list of instruments

### ISSUE THREAD

**Issue by pickleshy** [nkkl/orchestral#12]
Reproduced on desktop and mobile in Chrome. Only happens on "back," never when just loading the site.
![image](https://cloud.githubusercontent.com/assets/5819702/11056382/335139f2-8736-11e5-846f-09b27b6c150f.png)

**Comment by nkkl** [comment]
Fixed in https://github.com/nkkl/orchestral/commit/56f35d44fb35dfbb20a6bae2670dc68623fb7a10 by preventing the browser from caching the page, which forces a refresh when users navigate back.
