### ISSUE TITLE
Breakpoints not identical for all sections of the site?

### ISSUE THREAD

**Issue by pickleshy** [nkkl/orchestral#13]
At a certain width (around 986), the instrument section goes mobile without styles, and the top and bottom sections still function as the desktop version.

![image](https://cloud.githubusercontent.com/assets/5819702/11056485/1926c92e-8737-11e5-8375-dbb853f3fe3d.png)

**Comment by nkkl** [comment]
Breakpoints in code are <=991 and >=992, so this shouldn't be happening. May be an issue with device reporting size strangely.

**Comment by nkkl** [comment]
Unable to repro on my device.

**Comment by pickleshy** [comment]
Ok. FWIW, I saw it on desktop.
