### ISSUE TITLE
Increase line spacing on homepage (mobile only)

### ISSUE THREAD

**Issue by pickleshy** [nkkl/orchestral#14]
• Add space under page title
• Increase line height for counter text

![image](https://cloud.githubusercontent.com/assets/5819702/11056512/7271233a-8737-11e5-9489-251862f42309.png)

**Comment by nkkl** [comment]
Fixed in https://github.com/nkkl/orchestral/commit/56f35d44fb35dfbb20a6bae2670dc68623fb7a10
