### ISSUE TITLE
Add space below H2s on Terms page

### ISSUE THREAD

**Issue by pickleshy** [nkkl/orchestral#15]
H2s are crowded, can we give them some room?

![image](https://cloud.githubusercontent.com/assets/5819702/11056532/9f9535ea-8737-11e5-8950-3787a3830736.png)

**Comment by nkkl** [comment]
How high pri is this? I don't expect anyone to actually click through to this page.

**Comment by pickleshy** [comment]
Ok to defer. Just wanted it to look respectable and authoritative bc it's
the legal stuff.
