### ISSUE TITLE
Change '1/46 students sponsored' to '1/46 musicians sponsored'

### ISSUE THREAD

**Issue by pickleshy** [nkkl/orchestral#16]
Whoops, they're not all students! Can you change "students sponsored" to "musicians sponsored"?

![image](https://cloud.githubusercontent.com/assets/5819702/11056611/9164f8ba-8738-11e5-9fac-184a0a2d67c7.png)

**Comment by nkkl** [comment]
Fixed in https://github.com/nkkl/orchestral/commit/56f35d44fb35dfbb20a6bae2670dc68623fb7a10
