### ISSUE TITLE
Adjust date counter so that on 11/18 there will be 1 day to go

### ISSUE THREAD

**Issue by pickleshy** [nkkl/orchestral#18]
Currently, there will be "0 days to go" on 11/18, but the campaign will still be running until EOD. Can you change the counter so that it will show "1 day to go" on the 18th?

**Comment by nkkl** [comment]
Fixed in https://github.com/nkkl/orchestral/commit/3daf929f753cb0c42a37f35c9fa3a45ddcd43afb
