### ISSUE TITLE
Clicking PayPal button, then dismissing PayPal window, leaves glowy blue line around PayPal button

### ISSUE THREAD

**Issue by pickleshy** [nkkl/orchestral#2]
![image](https://cloud.githubusercontent.com/assets/5819702/10865615/309190be-7fce-11e5-9485-11f30fc96340.png)

**Comment by nkkl** [comment]
Unfortunately not fixable.

Because that button is part of an iframe that is being pulled from PayPal's servers, we don't actually have access to any of the HTML or CSS and cannot modify it.

**Comment by pickleshy** [comment]
Thanks for looking into it – sorry it was such a huge pain!
