### ISSUE TITLE
Add Terms of Use page

### ISSUE THREAD

**Issue by pickleshy** [nkkl/orchestral#9]
**Braintree requirements**
In order to comply with Visa and MasterCard regulations, there are certain items that must be present on your website and/or mobile app before Braintree can guarantee that we will disburse funds to your bank account... (source: https://articles.braintreepayments.com/reference/security/ecommerce-website-requirements)

Add link "Terms of use" in footer and create new page: 
https://orchestral.herokuapp.com/termsandprivacy

Content for the page:

<h2>Refund policy</h2>

<p>If you believe you have made a donation in error, please contact us at info@seattlecollaborativeorchestra.org and we will refund your donation.</p>

<h2>Privacy policy</h2>

<p>Your name and email address are collected for the purpose of processing your donation. We will never disclose your personal information without your explicit consent.</p>

<h2>Terms and Conditions ("Terms")</h2>

<p>Last updated: November 10, 2015</p>

<p>Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the https://orchestral.herokuapp.com/ website (the "Service") operated by The Live Music Project ("us", "we", or "our").</p>

<p>Your access to and use of the Service is conditioned upon your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who wish to access or use the Service.</p>

<p><strong>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you do not have permission to access the Service.</strong></p>

<p><strong>Intellectual Property</strong></p>

<p>The Service and its original content, features and functionality are and will remain the exclusive property of The Live Music Project and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of The Live Music Project.</p>    

<p><strong>Links To Other Web Sites</strong></p>

<p>Our Service may contain links to third party web sites or services that are not owned or controlled by The Live Music Project.</p>

<p>The Live Music Project has no control over, and assumes no responsibility for the content, privacy policies, or practices of any third party web sites or services. We do not warrant the offerings of any of these entities/individuals or their websites.</p>

<p>You acknowledge and agree that The Live Music Project shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such third party web sites or services.</p>

<p>We strongly advise you to read the terms and conditions and privacy policies of any third party web sites or services that you visit.</p>

<p><strong>Indemnification</strong></p>

<p>You agree to defend, indemnify and hold harmless The Live Music Project and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of a) your use and access of the Service, or b) a breach of these Terms.</p>    
    

<p><strong>Limitation Of Liability</strong></p>

<p>In no event shall The Live Music Project, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.</p>

<p><strong>Disclaimer</strong></p>

<p>Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.</p>

<p>The Live Music Project its subsidiaries, affiliates, and its licensors do not warrant that a) the Service will function uninterrupted, secure or available at any particular time or location; b) any errors or defects will be corrected; c) the Service is free of viruses or other harmful components; or d) the results of using the Service will meet your requirements.</p>

<p><strong>Exclusions</strong></p>

<p>Some jurisdictions do not allow the exclusion of certain warranties or the exclusion or limitation of liability for consequential or incidental damages, so the limitations above may not apply to you.</p>

<p><strong>Governing Law</strong></p>

<p>These Terms shall be governed and construed in accordance with the laws of Washington, United States, without regard to its conflict of law provisions.</p>

<p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have had between us regarding the Service.</p>

<p><strong>Changes</strong></p>

<p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will provide at least 60 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>

<p>By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use the Service.</p>

<p><strong>Contact Us</strong></p>

<p>If you have any questions about these Terms, please contact us: info@livemusicproject.org.</p>

**Comment by nkkl** [comment]
Resolved in https://github.com/nkkl/orchestral/commit/5903c0aea0a84644b87ace951855578d5b17db68
